# Generated by Django 6.1 on 2026-09-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barberias',
            fields=[
                ('idbarberia', models.AutoField(db_column='idBarberia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
            options={
                'db_table': 'Barberias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barberos',
            fields=[
                ('idbarbero', models.AutoField(db_column='idBarbero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=255)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Barberos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('idcita', models.AutoField(db_column='idCita', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.DateTimeField()),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('telefono', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompra', models.AutoField(db_column='idCompra', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('total', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('iddetalle', models.AutoField(db_column='idDetalle', primary_key=True, serialize=False)),
                ('subtotal', models.PositiveIntegerField(db_column='subTotal')),
                ('cantidad', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Detalles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idfactura', models.AutoField(db_column='idFactura', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('idfavoritos', models.AutoField(db_column='idFavoritos', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Favoritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('idnotificacion', models.AutoField(db_column='idNotificacion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('leida', models.IntegerField()),
            ],
            options={
                'db_table': 'Notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idpago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('monto', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('metodopago', models.CharField(blank=True, db_column='metodoPago', max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personalizaciones',
            fields=[
                ('idpersonalizacion', models.AutoField(db_column='idPersonalizacion', primary_key=True, serialize=False)),
                ('logourl', models.CharField(db_column='logoUrl', max_length=255)),
                ('colorprimario', models.CharField(db_column='colorPrimario', max_length=255)),
                ('colorsecundario', models.CharField(db_column='colorSecundario', max_length=255)),
                ('splashurl', models.CharField(db_column='splashUrl', max_length=255)),
            ],
            options={
                'db_table': 'Personalizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resenas',
            fields=[
                ('idresena', models.AutoField(db_column='idResena', primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Resenas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idservicio', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('precio', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('idsuscripcion', models.AutoField(db_column='idSuscripcion', primary_key=True, serialize=False)),
                ('plan', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
            ],
            options={
                'db_table': 'Suscripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('telefono', models.PositiveIntegerField(unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('clave', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('rol', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
